### ISSUE TITLE
Why another guzzle bundle?

### ISSUE THREAD

**Issue by gimler** [orkestra/OrkestraGuzzleBundle#14]
Hello,

why you create another guzzle bundle and not contribute to the existing one https://github.com/ddeboer/GuzzleBundle?

**Comment by zachbadgett** [comment]
Although I feel ddeboar/GuzzleBundle is a good bundle, it didn't meet my needs; I initially was going to contribute, but I felt the bundle went in a different direction than the bundle I imagined.
